#ifndef CRCTOOLPLUGIN_GLOBAL_H
#define CRCTOOLPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CRCTOOLPLUGIN_LIBRARY)
#  define CRCTOOLPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define CRCTOOLPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // CRCTOOLPLUGIN_GLOBAL_H
