#ifndef USERACCOUNTSYSTEM_GLOBAL_H
#define USERACCOUNTSYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USERACCOUNTSYSTEM_LIBRARY)
#  define USERACCOUNTSYSTEM_EXPORT Q_DECL_EXPORT
#else
#  define USERACCOUNTSYSTEM_EXPORT Q_DECL_IMPORT
#endif

#endif // USERACCOUNTSYSTEM_GLOBAL_H
